# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartRide' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SmartRide
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTImage',
    # Add any additional subspecs you need
  ]

  # Add your native dependencies here. Example:
  # pod 'MyNativeModule', :path => '../node_modules/my-native-module'

  # Automatically link your native modules
  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'

  target 'SmartRideTests' do
    inherit! :complete
    # Pods for testing
  end

  # Post Install processing
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'React'
        target.remove_from_project
      end
    end
  end
end
